// <auto-generated />
using LexiconWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LexiconWebAppMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211207192226_More Person_Language data Seeded")]
    partial class MorePerson_LanguagedataSeeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LexiconWebApp.Models.CityModel", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "Roma",
                            CountryId = 2
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Berlin",
                            CountryId = 1
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Hanover",
                            CountryId = 1
                        },
                        new
                        {
                            CityId = 4,
                            CityName = "Gothenburg",
                            CountryId = 3
                        },
                        new
                        {
                            CityId = 5,
                            CityName = "Stockholm",
                            CountryId = 3
                        },
                        new
                        {
                            CityId = 6,
                            CityName = "Oslo",
                            CountryId = 4
                        });
                });

            modelBuilder.Entity("LexiconWebApp.Models.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Norway"
                        });
                });

            modelBuilder.Entity("LexiconWebApp.Models.LanguageModel", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            LanguageName = "German"
                        },
                        new
                        {
                            LanguageId = 2,
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            LanguageId = 3,
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            LanguageId = 4,
                            LanguageName = "italian"
                        });
                });

            modelBuilder.Entity("LexiconWebApp.Models.PersonLanguageModel", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("PersonId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Person_Language");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            LanguageId = 2
                        },
                        new
                        {
                            PersonId = 1,
                            LanguageId = 1
                        },
                        new
                        {
                            PersonId = 1,
                            LanguageId = 3
                        },
                        new
                        {
                            PersonId = 2,
                            LanguageId = 1
                        },
                        new
                        {
                            PersonId = 3,
                            LanguageId = 1
                        },
                        new
                        {
                            PersonId = 4,
                            LanguageId = 2
                        },
                        new
                        {
                            PersonId = 5,
                            LanguageId = 2
                        },
                        new
                        {
                            PersonId = 6,
                            LanguageId = 4
                        },
                        new
                        {
                            PersonId = 7,
                            LanguageId = 4
                        },
                        new
                        {
                            PersonId = 7,
                            LanguageId = 3
                        },
                        new
                        {
                            PersonId = 8,
                            LanguageId = 3
                        },
                        new
                        {
                            PersonId = 9,
                            LanguageId = 1
                        },
                        new
                        {
                            PersonId = 9,
                            LanguageId = 4
                        });
                });

            modelBuilder.Entity("LexiconWebApp.Models.PersonModel", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.HasIndex("CityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            CityId = 5,
                            FullName = "Johan Strom",
                            PhoneNumber = "+46-73225588"
                        },
                        new
                        {
                            PersonId = 2,
                            CityId = 2,
                            FullName = "Masoud Ozel",
                            PhoneNumber = "+49-55883211"
                        },
                        new
                        {
                            PersonId = 3,
                            CityId = 5,
                            FullName = "Angela Mark",
                            PhoneNumber = "+49-55880011"
                        },
                        new
                        {
                            PersonId = 4,
                            CityId = 4,
                            FullName = "Anna Maria",
                            PhoneNumber = "+46-732001874"
                        },
                        new
                        {
                            PersonId = 5,
                            CityId = 4,
                            FullName = "Samanta Hanson",
                            PhoneNumber = "+46-73201177"
                        },
                        new
                        {
                            PersonId = 6,
                            CityId = 1,
                            FullName = "Sandro Mazzola",
                            PhoneNumber = "+39-73225588"
                        },
                        new
                        {
                            PersonId = 7,
                            CityId = 1,
                            FullName = "Marco Tardeli ",
                            PhoneNumber = "+39-73225588"
                        },
                        new
                        {
                            PersonId = 8,
                            CityId = 6,
                            FullName = "Rita Nord",
                            PhoneNumber = "+47-73225008"
                        },
                        new
                        {
                            PersonId = 9,
                            CityId = 3,
                            FullName = "Michel Moler",
                            PhoneNumber = "+49-73225008"
                        });
                });

            modelBuilder.Entity("LexiconWebApp.Models.CityModel", b =>
                {
                    b.HasOne("LexiconWebApp.Models.CountryModel", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexiconWebApp.Models.PersonLanguageModel", b =>
                {
                    b.HasOne("LexiconWebApp.Models.LanguageModel", "Language")
                        .WithMany("Person_Language")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexiconWebApp.Models.PersonModel", "Person")
                        .WithMany("Person_Language")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LexiconWebApp.Models.PersonModel", b =>
                {
                    b.HasOne("LexiconWebApp.Models.CityModel", "City")
                        .WithMany("PeopleList")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
